import type { Metadata } from 'next';
import 'antd/dist/antd.css';
import './globals.css';

import LayoutHeaderItem from '@/compontents/layout/LayoutHeaderItem';

const ConfigMenus = [
  {
    label: 'main.json',
    value: 'main',
  },
  {
    label: 'text',
    value: 'sd',
  },
];

export const metadata: Metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <div className="flex items-center h-12 bg-slate-200 px-4">
          {ConfigMenus.map((config) => {
            return <LayoutHeaderItem key={config.value} {...config}></LayoutHeaderItem>;
          })}
        </div>

        <div className="h-[calc(100%-3rem)]">{children}</div>
      </body>
    </html>
  );
}
