'use client';
import type { Metadata } from 'next';
import './globals.css';
import 'antd/dist/antd.css';
import { usePathname, useRouter } from 'next/navigation';

import { classnames, spacing, sizing, typography } from 'tailwindcss-classnames';

const ConfigMenus = [
  {
    label: 'main.json',
    value: 'main',
  },
  {
    label: 'text',
    value: 'sd',
  },
];

export const metadata: Metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  const router = useRouter();
  const pathname = usePathname();
  return (
    <html lang="en">
      <body>
        <div className="flex items-center h-12 bg-slate-200 px-4">
          {ConfigMenus.map((config) => {
            return (
              <div
                className={classnames(
                  spacing('mr-4'),
                  sizing('h-6'),
                  typography(pathname.includes(config.value) ? 'text-cyan-600' : undefined)
                )}
                key={config.value}
                onClick={() => router.push(`${config.value}`)}
              >
                {config.label}
              </div>
            );
          })}
        </div>

        <div className="h-[calc(100%-3rem)]">{children}</div>
      </body>
    </html>
  );
}
