import type { Metadata } from 'next';
import 'antd/dist/antd.css';
import './globals.css';

const ConfigMenus = [
    {
        label: 'main.json',
        value: 'main.json',
    },
];

export const metadata: Metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body>
                <div className="flex items-center h-12 bg-slate-200 px-4">
                    {ConfigMenus.map((config) => {
                        return <div className="mr-4 h-6">{config.label}</div>;
                    })}
                </div>

                <div>{children}</div>
            </body>
        </html>
    );
}
